[project]
name = "ngobrol-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.124.4",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.1.0",
    "pymupdf>=1.26.7",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.27",
    "uuid>=1.30",
    "uvicorn>=0.38.0",
]
